services:
  keycloak:
    image: jboss/keycloak:15.0.0
    container_name: keycloak
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data/
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8080:8080"
volumes:
  keycloak_data:
