services:
  postgis:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgis-geoserver
    environment:
      POSTGRES_USER: geoserver
      POSTGRES_PASSWORD: geoserver
    volumes:
      - postgresql_data:/var/lib/postgresql/data:Z
    healthcheck:
      test: pg_isready -U geoserver -h localhost -t 5 || exit 1
      interval: 10s
      retries: 5
      timeout: 10s

  # Login: admin. Password: geoserver
  geoserver:
    image: docker.osgeo.org/geoserver:2.25.x
    container_name: geoserver
    ports:
      - "8080:8080"
    volumes:
      - ./data:/opt/geoserver/data_dir
      - ./additional_libs:/opt/additional_libs:Z
      - geo_data:/opt/geoserver_data
    environment:
      SKIP_DEMO_DATA: "true"
      CORS_ENABLED: "true"
      CORS_ALLOWED_ORIGINS: "*"
      CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      CORS_ALLOWED_HEADERS: "*"
      INSTALL_EXTENSIONS: "true"
      STABLE_EXTENSIONS: "gwc-s3,gdal"
      COMMUNITY_EXTENSIONS: "cog"
      POSTGRES_HOST: postgis
      POSTGRES_PORT: 5432
      POSTGRES_DB: geoserver
      POSTGRES_USERNAME: geoserver
      POSTGRES_PASSWORD: geoserver
      POSTGRES_JNDI_RESOURCE_NAME: jdbc/postgres
      EXTRA_JAVA_OPTS: "-Xms2g -Xmx2g"
    healthcheck:
      test: curl --fail "http://localhost:8080/geoserver/web/wicket/resource/org.geoserver.web.GeoServerBasePage/img/logo.png" || exit 1
      interval: 1m
      retries: 3
      timeout: 20s
    depends_on:
      - postgis

volumes:
  geo_data:
  postgresql_data: