services:
  #url: https://localhost:9443/
  portainer:
    image: portainer/portainer-ce:2.20.3-alpine
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
volumes:
  data:
