services:
  db:
    container_name: db-sonarqube
    image: postgres:13.3-alpine
    volumes:
      - db:/var/lib/postgresql
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_CONFIG:-config}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-user}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Login: admin. Password: admin
  sonarqube:
    image: sonarqube:9.9.3-community
    container_name: sonarqube
    ports:
      - '9000:9000'
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://${DB_HOST:-db}:${DB_PORT:-5432}/${DB_CONFIG:-config}
      SONAR_JDBC_USERNAME: ${DB_USER:-user}
      SONAR_JDBC_PASSWORD: ${DB_PASSWORD:-secret}

volumes:
  db:
  db-data:
  pgadmin-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_conf: