services:
  pgadmin4:
    image: dpage/pgadmin4:8.6
    container_name: pgadmin4
    ports:
        - '5050:80'
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@localhost.com
        PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
        - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data: