global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: true
    endpoint: "unix:///var/run/docker.sock"
  file:
    filename: "/etc/traefik/traefik.yml"

entryPoints:
  web:
    address: ":80"

http:
  routers:
    to-portainer:
      rule: Host(`localhost`) && PathPrefix(`/portainer`)
      service: portainer

  services:
    portainer:
      loadBalancer:
        servers:
          - url: "http://portainer-snippets-docker:9000/"
